### ISSUE TITLE
Artwork/Sound for OinkPop

### ISSUE THREAD

**Issue by lapubell** [assertchris/games#1]
Howdy!

I was at the PHP meetup last night and talked with you about OinkPop in python. I pulled this repo down to see if I could get at the original artwork/sound, but it looks like that's all bundled up in some godot binary format. Wanna let me know how I can peek at these assets?

Thanks!

**Comment by assertchris** [comment]
My email is cgpitt@gmail.com. If you send me an email then I can reply with the assets.

**Comment by lapubell** [comment]
cool!

better yet, can you just add them to this new repo I created? I'll add you as a collaborator. This is gonna be fun. :)
https://github.com/lapubell/oinkpop

**Comment by lapubell** [comment]
love it, thanks!
